######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 5 14:50:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += confcreationwidget.h mainwindow.h
FORMS += confcreationwidget.ui mainwindow.ui
SOURCES += confcreationwidget.cpp main.cpp mainwindow.cpp
